language: node_js
node_js:
- 12
cache:
  directories:
  - node_modules
install: npx lerna bootstrap
jobs:
  include:
  - stage: test
    script:
    - npx lerna run --scope coved-server test
    - npx lerna run --scope coved-client test
    - npx lerna run lint
  - stage: publish
    if: branch = master
    script:
    - git checkout master
    - npx lerna version patch --yes --amend
before_install:
- openssl aes-256-cbc -K $encrypted_ee58d8b33dc6_key -iv $encrypted_ee58d8b33dc6_iv
  -in service_account.json.enc -out packages/server/service_account.json -d
deploy:
  TWILIO_SID:
    secure: ZB2VX1Lf7f11SasLHt2lMDdsfYE5/IQ4K6NZB2d/hQhenYsw8qAZJGKil5ab159kQ2RGn/FYNfZNgBoGtXbRseetBT8vprdOGI3/6SBmcDovamNCSN9E0z4rv4KY8ykWauxveIthFiFaA2KGTxGfBjkidPrnlCQ3VioS8T+Y8PF1Qs6ibHsCCdkUZ3EAsZNOqmBGOr55nMGwG3dFjbtVv+nNXocD+Lj+MBDd3At3SCXhBSYrLAIlbvCY0eMHxzISUAA6ejMJ2ONHoVwjuHY7lQ1SvZvIcPyO+4mzpRNd6Ka/Tkm/01LXgMTx7IIioFT6X9StUXPDYphEQDaFEW4R6L/UojX7W+KDX2fuGzyfiJEBe7eXnC4Cdbr4X9hu/EvxE8/PgisKAjblMDWuS4gnK605fro7WuidvtVMoopQjDVvh/YakgDGD1tZkxQoO5PuivYphVB53gRvSpz/KEIYsI7g9J5KHZrAiVIhc6SZa6fPgrr2Yn+bquUgwNbZwbKAkIWh5Jc8INR723tC8iuH6fs+7Njyqf5DbXbbueYjNSeJ3iFP25lodr5EaAW/Jli5IN8e3zbKT7iNP7EL15QF74PeOpV2fK1DBG+F32UmRldypulyUZ16q3mm5jyJ7W9wwq8ejuRO0LID5qblEaxDG6lLeE5i2zwO+SWScQaRYbA=
  TWILIO_AUTH_TOKEN:
    secure: CG0qYD6p2F8dAEQHSZXJLRMtopxgh7nq+LYo3ze4xIOjs3ty+hbjjtbMDMoOSaq7rT847FyAJiy+aIusmahy93XRmdTadsFKRcBtfA5LYYb/it2kmoIa+3btQQ8NxCiV4SGS+daMccF/k0F/Qo98mdt6vZNITOMmXwdT3OrUuTA4Ef1k3yFF8UToabKEErYDIFS4RsUrT1nhXTU95H+KJwfRf6AjV/AXCLrUK5YnCWS1wMxE46dH77nSIETygJlTOkcfyko/ix9uPJWt643Bb6Hf9UbHu04La8IvAx4hC2snfP7ywWyZ0lY3AhmV2VHnQzMpiBYVOn+g57XYGM2yHF5MH3whOmGe9u/LAg4w+ZCc6BZcR1VFXjrhrYHe47uxuuwjLxONdX/6rYrifJfo1TZ8gXv+LvwrCkb7eLICnwbEep6nEC6PdryH32a19LSUeqnOwH+f8mXl3nHGl9Gg7mc7myeZNAAxzegIJsGFDRQ62ceRHy/UK7fBzLzYyzoANCJRn3JfQ6VCenk0CVZ07j9/ek1kfTFlX6jRoNYNJ7pdUSqj0M1oviCHy1FehhqbKZo6oprn6gMAiVtCbmd2+atCb9q5fH0TrmgT5rkMYFo+Os8HFG1Yx2VwMmMa8ZzR+ugFc51bj9yn0+dBviEb/Vxo/lve+5evkjIumiJeKc0=
